language: node_js
node_js:
  - 14
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - stable
script:
  - yarn test
  - yarn build
deploy:
  provider: netlify
  site: 748ad1af-f062-4bb5-b15d-10ec46f4c1dc
  auth: $NETLIFY_TOKEN
  edge: true
  prod: true
  dir: dist/
  message: $TRAVIS_COMMIT_MESSAGE
