language: node_js
node_js:
  - 14
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - stable
script:
  - yarn test
  - yarn build
deploy:
  provider: netlify
  site: 4b94c090-b000-4b5a-b055-ace965e32c23
  auth: $NETLIFY_TOKEN
  edge: true
  prod: true
  dir: dist/
  message: $TRAVIS_COMMIT_MESSAGE
